version: 1.0.{build}
os: Visual Studio 2015

before_build:
- nuget restore OmniXaml.sln

environment:
  myget_key:
    secure: 1/e8AMVotuUIufSGUDn4MZubYFZSqXpmRFeRgcrIRZjiyoQpnZR/lSawMCL4A2SF

configuration:
  - Release

after_test:
- ps: nuget\build-appveyor.ps1

artifacts:
  - path: nuget\*.nupkg

build:
  project: OmniXaml.sln
  verbosity: minimal
